services:
  frontend-dev:
    build:
      context: .
      target: development
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3333}
    init: true
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - type: volume
        source: frontend_node_modules
        target: /home/node/app/node_modules

  frontend-tools:
    build:
      context: .
      target: tools
    environment:
      CI: 'true'
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3333}
    init: true
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - type: volume
        source: frontend_node_modules
        target: /home/node/app/node_modules

  frontend-production:
    build:
      context: .
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3333}
    ports:
      - '${FRONTEND_PORT:-3000}:80'

volumes:
  frontend_node_modules:
