name: Test and Build

on:
  push:
    branches:
      - task/lboi/use_chaye_api_backend
  pull_request:
    branches:
      - task/lboi/use_chaye_api_backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6.0.3

      - name: Install nodejs
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Run typecheck
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6.0.3

      - name: Install nodejs
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        env:
          VITE_API_URL: http://localhost:3333
        run: npm run build

      - name: Build production Docker image
        run: docker build --build-arg VITE_API_URL=http://localhost:3333 -t chaye-web-frontend .
